const app=document.getElementById('app');
const days=['','一','二','三','四','五'];
const titles={dashboard:'首頁',profile:'個人資料',search:'課程查詢',courses:'選課系統',schedule:'我的課表',grades:'成績查詢'};
const symbols={dashboard:'⌂',profile:'◎',search:'⌕',courses:'＋',schedule:'▦',grades:'▥'};
let selected;try{selected=JSON.parse(localStorage.getItem('nqu-hw2-courses'));if(!Array.isArray(selected))selected=[...DEFAULT_IDS];selected=selected.filter(id=>COURSES.some(c=>c.id===id));}catch{selected=[...DEFAULT_IDS]}
let filterText='',filterDay='',filterStatus='';
const chosen=()=>COURSES.filter(c=>selected.includes(c.id));
const credits=()=>chosen().reduce((n,c)=>n+c.credits,0);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=c=>`週${days[c.day]} · 第 ${c.start}–${c.end} 節`;
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
function save(){try{localStorage.setItem('nqu-hw2-courses',JSON.stringify(selected))}catch{toast('瀏覽器無法儲存資料，重新整理後可能重設。')}}
function toggle(id){const c=COURSES.find(c=>c.id===id);if(selected.includes(id)){selected=selected.filter(x=>x!==id);toast(`已退選「${c.name}」`)}else{const conflict=chosen().find(x=>x.day===c.day&&x.start<=c.end&&c.start<=x.end);if(conflict){toast(`時間衝突：與「${conflict.name}」重疊`);return}if(credits()+c.credits>25){toast('加選後超過 25 學分上限');return}selected.push(id);toast(`已加選「${c.name}」`)}save();render()}
function login(){app.innerHTML=`<div class="login"><section class="login-art"><div class="brand"><span class="mark">NQU</span><div><strong>NQU Portal</strong><small>STUDENT INFORMATION</small></div></div><div><div class="eyebrow" style="color:#78adff">YOUR CAMPUS, CONNECTED</div><h1>學習的每一步，<br>在這裡展開。</h1><p>課程、課表與學習資訊，<br>一個入口，掌握你的校園生活。</p></div><small>國立金門大學 · 校務系統課程專案</small></section><section class="login-form"><form class="login-box" id="loginForm"><p class="eyebrow">WELCOME BACK</p><h1>登入學生入口</h1><p class="muted">歡迎回來，開始今天的學習旅程。</p><label for="studentId">學號</label><input id="studentId" name="studentId" autocomplete="username" value="111210552" required><label for="password">密碼</label><input id="password" name="password" type="password" autocomplete="current-password" placeholder="輸入示範密碼" required><button class="btn" type="submit">登入</button><div class="error" id="loginError" role="alert"></div><div class="login-note">示範帳號：111210552<br>示範密碼：123456<br>此為課程專案，請勿輸入校務系統真實密碼。</div></form></section></div>`;document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();if(document.getElementById('studentId').value.trim()===STUDENT.id&&document.getElementById('password').value==='123456'){sessionStorage.setItem('nqu-hw2-login','true');location.hash='dashboard';render()}else document.getElementById('loginError').textContent='學號或密碼不正確，請使用示範帳號。'}}
function stats(){return `<div class="stats"><div class="stat"><div><div class="stat-label">本學期修習學分</div><div class="stat-value">${credits()}<span>學分</span></div><small>115 學年度第 1 學期</small></div><span class="stat-icon">▥</span></div><div class="stat"><div><div class="stat-label">已選課程</div><div class="stat-value">${chosen().length}<span>門</span></div><small>同步更新課表</small></div><span class="stat-icon">▦</span></div><div class="stat"><div><div class="stat-label">就讀班級</div><div class="stat-value" style="font-size:28px">資工四</div><small>資訊工程學系</small></div><span class="stat-icon">◎</span></div></div>`}
function dashboard(){const day=new Date().getDay();const today=chosen().filter(c=>c.day===day).sort((a,b)=>a.start-b.start);return `${stats()}<div class="grid"><div><section class="panel"><div class="panel-head"><h2>今日課程 <span class="muted">· ${today.length} 門</span></h2><a class="text-link" href="#schedule">完整課表</a></div><div class="panel-body">${today.length?today.map(c=>`<div class="course-card"><div class="period"><strong>${c.start}–${c.end}</strong>節次</div><div class="course-detail"><strong>${c.name}</strong><small>${c.english}</small><span class="tag">${c.credits} 學分</span> <span class="muted">${c.room}</span></div></div>`).join(''):'<div class="empty">今天沒有課程，留點時間給自己。</div>'}</div></section><section class="panel"><div class="panel-head"><h2>本週課程概覽</h2><span class="muted">週一至週五</span></div><div class="panel-body"><div class="week-table"><div></div>${days.slice(1).map(d=>`<div class="day">週${d}</div>`).join('')}<div class="day">上午</div>${[1,2,3,4,5].map(d=>mini(d,1,4)).join('')}<div class="day">下午</div>${[1,2,3,4,5].map(d=>mini(d,5,8)).join('')}</div></div></section></div><div><div class="semester-card"><span class="eyebrow" style="color:#82b5ff">CURRENT SEMESTER</span><h2 style="margin-top:8px">115 學年度 · 第 1 學期</h2><p>好好學習，也記得好好生活。</p><div class="progress" aria-hidden="true"><i></i></div><p style="margin-bottom:0">林小蓮 · 111210552</p></div><section class="panel"><div class="panel-head"><h2>快速前往</h2></div><div class="panel-body quick-links">${['courses','schedule','grades','profile'].map(k=>`<a href="#${k}"><span class="icon" style="color:#2463eb">${symbols[k]}</span>${titles[k]}</a>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>學習提醒</h2><span class="tag">本學期</span></div><div class="panel-body"><div class="notice">加退選後，請確認學分與課表是否符合你的安排。<small>選課資訊會保存在目前的瀏覽器。</small></div><div class="muted">本學期成績尚未公布。<br>教室與教師資訊待確認。</div></div></section></div></div>`}
function mini(day,start,end){const list=chosen().filter(c=>c.day===day&&c.start<=end&&c.end>=start);return `<div class="mini ${list.length?'filled':''}">${list.length?list.map(c=>c.name).join('<br>'):'—'}</div>`}
function tableRows(){const list=COURSES.filter(c=>(c.name+c.english+c.id).toLowerCase().includes(filterText.toLowerCase())&&(!filterDay||c.day===Number(filterDay))&&(!filterStatus||((filterStatus==='selected')===selected.includes(c.id))));return list.length?list.map(c=>`<tr><td>${c.id}</td><td><strong>${c.name}</strong><small>${c.english}</small>${c.type==='示範課程'?'<span class="tag" style="margin-top:7px">示範課程</span>':''}</td><td>${c.credits}</td><td>${when(c)}<small>${c.room}</small></td><td>${selected.includes(c.id)?'<span class="tag">已選</span>':'<span class="muted">未選</span>'}</td><td><button class="btn ${selected.includes(c.id)?'drop':''}" data-course="${c.id}">${selected.includes(c.id)?'退選':'加選'}</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">找不到符合條件的課程。</td></tr>'}
function courses(){return `<div class="summary-bar"><span>已選 <strong>${chosen().length} 門</strong></span><span>修習 <strong>${credits()} 學分</strong></span><span class="muted">學分上限 25 · 自動檢查時間衝突</span></div><div class="toolbar"><input class="search" id="courseSearch" type="search" aria-label="搜尋課程" placeholder="搜尋課程名稱或代碼" value="${escapeHTML(filterText)}"><select id="dayFilter" aria-label="篩選上課日"><option value="">所有上課日</option>${days.slice(1).map((d,i)=>`<option value="${i+1}" ${filterDay==i+1?'selected':''}>週${d}</option>`).join('')}</select><select id="statusFilter" aria-label="篩選選課狀態"><option value="">所有狀態</option><option value="selected" ${filterStatus==='selected'?'selected':''}>已選課程</option><option value="available" ${filterStatus==='available'?'selected':''}>未選課程</option></select></div><section class="panel table-wrap"><table><thead><tr><th>課程代碼</th><th>課程名稱</th><th>學分</th><th>上課時間</th><th>狀態</th><th>操作</th></tr></thead><tbody id="courseRows">${tableRows()}</tbody></table></section><p class="muted">前四門依提供的課表建立；「示範課程」僅供功能展示，並非正式開課資訊。</p>`}
function schedule(){let body='';for(let period=1;period<=8;period++){body+=`<tr><td>第 ${period} 節</td>`;for(let day=1;day<=5;day++){const c=chosen().find(c=>c.day===day&&c.start<=period&&c.end>=period);if(c&&c.start<period)continue;body+=c?`<td rowspan="${c.end-c.start+1}"><div class="schedule-event ${c.color}"><strong>${c.name}</strong><small>${c.id} · ${c.credits} 學分</small><small>${c.room}</small></div></td>`:'<td></td>'}body+='</tr>'}return `<div class="toolbar"><span class="summary-bar" style="margin:0">${chosen().length} 門課程 · ${credits()} 學分</span><button class="btn secondary" id="printSchedule">列印課表</button></div><section class="panel table-wrap"><table class="schedule-table"><thead><tr><th style="width:80px">節次</th>${days.slice(1).map(d=>`<th>星期${d}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></section><p class="muted">課表依選課結果即時更新；節次以提供的課表為準。</p>`}
function profile(){return `<div class="profile"><section class="panel profile-card"><div class="avatar">蓮</div><h2>林小蓮</h2><p class="muted">111210552</p><span class="tag">資工四</span></section><section class="panel"><div class="panel-head"><h2>學生基本資料</h2><span class="tag">在學</span></div><dl class="details"><div><dt>中文姓名</dt><dd>林小蓮</dd></div><div><dt>學號</dt><dd>111210552</dd></div><div><dt>就讀學校</dt><dd>國立金門大學</dd></div><div><dt>系所</dt><dd>資訊工程學系</dd></div><div><dt>班級</dt><dd>資工四</dd></div><div><dt>目前學期</dt><dd>115 學年度第 1 學期</dd></div></dl></section></div>`}
function grades(){return `<div class="notice">本學期成績尚未公布。公布前不計算學期平均或 GPA。</div><section class="panel table-wrap"><table><thead><tr><th>課程代碼</th><th>課程名稱</th><th>學分</th><th>成績</th></tr></thead><tbody>${chosen().length?chosen().map(c=>`<tr><td>${c.id}</td><td>${c.name}</td><td>${c.credits}</td><td><span class="tag">尚未公布</span></td></tr>`).join(''):'<tr><td colspan="4" class="empty">目前沒有已選課程。</td></tr>'}</tbody></table></section>`}
function render(){if(sessionStorage.getItem('nqu-hw2-login')!=='true'){login();return}let page=location.hash.slice(1)||'dashboard';if(!titles[page])page='dashboard';const date=new Date().toLocaleDateString('zh-TW',{month:'long',day:'numeric',weekday:'long'});app.innerHTML=`<aside class="sidebar" id="sidebar"><a class="brand" href="#dashboard"><span class="mark">NQU</span><div><strong>NQU Portal</strong><small>學生資訊入口</small></div></a><div class="nav-label">STUDENT WORKSPACE</div><nav class="nav" aria-label="主要導覽">${Object.keys(titles).map(k=>`<a href="#${k}" class="${page===k?'active':''}" ${page===k?'aria-current="page"':''}><span class="icon" aria-hidden="true">${symbols[k]}</span>${titles[k]}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="student-mini"><div class="avatar">蓮</div><div><strong>林小蓮</strong><small>111210552 · 資工四</small></div></div><button class="logout" id="logout"><span>↪</span>登出帳號</button></div></aside><main class="main"><header class="topbar"><button class="mobile-menu" id="mobileMenu" aria-label="開啟導覽選單" aria-expanded="false">☰</button><div class="breadcrumb">學生入口 <b>/　${titles[page]}</b></div><div class="top-right"><span class="semester">115 學年度第 1 學期</span><span>林小蓮</span><div class="avatar">蓮</div></div></header><div class="content"><div class="heading"><div><p class="eyebrow">${page==='dashboard'?'MY CAMPUS':page==='schedule'?'WEEKLY TIMETABLE':page==='profile'?'STUDENT PROFILE':page==='grades'?'ACADEMIC RECORD':'COURSE WORKSPACE'}</p><h1>${page==='dashboard'?'歡迎回來，林小蓮':titles[page]}</h1><p class="muted">${page==='dashboard'?'新的一天，讓學習井然有序。':page==='schedule'?'每一堂課，都是向前的一步。':page==='profile'?'你的校園身分與學籍資訊。':page==='grades'?'查看本學期修習課程與成績狀態。':'找到適合你的課程，安排自己的學習節奏。'}</p></div><span class="date-chip">${date}</span></div>${page==='dashboard'?dashboard():page==='profile'?profile():page==='schedule'?schedule():page==='grades'?grades():courses()}<footer class="footer"><span>NQU Portal · 國立金門大學校務系統課程專案</span><span>林小蓮 111210552 · HW2</span></footer></div></main>`;document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('nqu-hw2-login');location.hash='';login()};document.getElementById('mobileMenu').onclick=e=>{const open=document.getElementById('sidebar').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))};bindCourses();if(document.getElementById('courseSearch')){document.getElementById('courseSearch').oninput=e=>{filterText=e.target.value;updateRows()};document.getElementById('dayFilter').onchange=e=>{filterDay=e.target.value;updateRows()};document.getElementById('statusFilter').onchange=e=>{filterStatus=e.target.value;updateRows()}}if(document.getElementById('printSchedule'))document.getElementById('printSchedule').onclick=()=>window.print()}
function bindCourses(){document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>toggle(b.dataset.course))}function updateRows(){document.getElementById('courseRows').innerHTML=tableRows();bindCourses()}
window.addEventListener('hashchange',()=>{filterText='';filterDay='';filterStatus='';render()});render();
